sudo: required


language: java

jdk: oraclejdk8

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t sesamcommunity/jdbc .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sesamcommunity/jdbc:latest;
    fi
